name: kchess
description: "Local chess analysis for Android and Windows."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  path: ^1.8.3
  ffi: ^2.1.4
  file_picker: ^12.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.3.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  sqflite: ^2.4.4
  sqflite_common_ffi: ^2.4.3

dev_dependencies:
  path: ^1.8.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/analysis_img/
    - assets/icons/
    - ../img/
    - assets/opening_book.kcb
    - assets/opening_names.kco
