#include "interaction/interaction_regression_cases.h"

namespace kchess::ai::interaction {

const std::vector<InteractionRegressionCase>& interaction_regression_cases() {
  static const std::vector<InteractionRegressionCase> cases = {
      {"start_game_de_reported",
       "lass uns einer partie spielen",
       true,
       {"start_game"},
       {"start_stockfish_game"},
       false,
       "start position may be available; must remain app_action, not position analysis"},
      {"start_game_en_reported",
       "let us start a game",
       true,
       {"start_game"},
       {"start_stockfish_game"},
       false,
       "start position may be available; must remain app_action, not position analysis"},
      {"start_game_ar",
       "لنلعب مباراة",
       true,
       {"start_game"},
       {"start_stockfish_game"},
       false,
       "Arabic direct game request must resolve without local model or provider routing"},
      {"start_game_black_en",
       "I want to play black.",
       true,
       {"start_game"},
       {"start_stockfish_game"},
       false,
       "explicit player color is a native action parameter and must reach client action transport"},
      {"start_game_elo_en",
       "Start a game at 1800 Elo.",
       true,
       {"start_game"},
       {"change_rating", "start_human_bot"},
       false,
       "explicit game Elo configures the opponent and must not become a rating prediction request"},
      {"negative_opening_why_de",
       "Warum sollte ich mit e4 anfangen?",
       true,
       {"explain"},
       {"answer_with_evidence"},
       true,
       "opening explanation must never trigger start_game"},
      {"negative_last_game_en",
       "What do you think about my last game?",
       true,
       {},
       {"answer_with_evidence"},
       true,
       "ordinary chess conversation must never trigger start_game from the word game"},
      {"worst_move_material_loss",
       "What is the worst move here if I want to see the move that loses material?",
       true,
       {"find_worst", "current_position", "material_loss"},
       {"analyze_position", "show_candidates", "compare_moves"},
       true,
       "position available"},
      {"human_1300_prediction",
       "What would a 1300 Elo player most likely play here?",
       true,
       {"predict", "current_position", "human_likelihood", "rating_prediction"},
       {"analyze_position"},
       true,
       "position available; deterministic parameter parser must capture elo=1300"},
      {"show_active_tactic_followup",
       "wie?",
       false,
       {},
       {"show_line"},
       false,
       "active_line_id and tactic evidence available"},
      {"show_it_followup",
       "zeig mal",
       false,
       {},
       {"show_line"},
       false,
       "active_line_id available"},
      {"why_followup",
       "warum?",
       false,
       {},
       {"explain_line"},
       true,
       "active_line_id plus active_evidence_id available"},
      {"human_game_with_live_coaching",
       "Spiel gegen mich wie ein 1800er und gib mir während der Partie Tipps.",
       true,
       {"start_game", "human_style", "live_coaching", "answer"},
       {"change_rating", "start_human_bot", "enable_live_coaching", "answer_with_evidence"},
       true,
       "mixed native game action plus language acknowledgement; deterministic parameter parser must capture elo=1800"},
      {"start_game_and_explain_future_mistakes",
       "Starte eine Partie und erkläre mir währenddessen meine Fehler.",
       true,
       {"start_game", "live_coaching", "answer"},
       {"start_stockfish_game", "enable_live_coaching", "answer_with_evidence"},
       true,
       "future live coaching must not become immediate find_mistake/position analysis"},
      {"board_only_show_move",
       "Zeig mir den Zug auf dem Brett.",
       true,
       {"show_move"},
       {"show_move"},
       false,
       "active_move_uci available"},
  };
  return cases;
}

}  // namespace kchess::ai::interaction
